### ISSUE TITLE
When you edit a comment that doesn’t include muck to include muck the bot doesn’t work

### ISSUE THREAD

**Issue by PoIygon** [hananelroe/muck-chains-stopper-bot#9]
The title explains it all

A post on the Dani dev subreddit said that if you make a comment that doesn’t have the word muck to include the word muck by editing it, the bot doesn’t shut the person.

proof: https://www.reddit.com/r/DaniDev/comments/rjials/lmao/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by hananelroe** [comment]
We know, we don't know if we can listen to comment edits
